spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: mycloud-config-gcj-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: mycloud-config-gcj-test